feat:keep webpack alias and plugins instead of create new
ant-tool/atool-doc pull request #42
Opened 2017-04-17 09:02 UTC by qiuyuntao

In my project's `webpack.config.js`, I have `alias` and `plugins` myself. Keep it instead of discarding them

2017-04-17 10:38 UTC, jaredleechn requested changes

2017-04-17 10:38 UTC, jaredleechn commented on src/getWebpackConfig.js
> +  webpackConfig.plugins.push(
这个 plugins 这里情况比较复杂，当时强制覆盖的目的是干掉 extractTextPlugin，因为拿不到 class，不能通过 instaceof 来判断

关于 plugins 的先 revert 掉吧，我来在 atool-build 层面协同处理这个问题，对于最终使用来说，webpackConfig.plugins.push 就可以～

2017-04-17 11:19 UTC, qiuyuntao commented on src/getWebpackConfig.js
> +  webpackConfig.plugins.push(
好 那我改下，先弄alias吧

2017-04-18 06:08 UTC, jaredleechn approved these changes

2017-04-18 06:08 UTC, jaredleechn commented
+1

2017-04-18 06:09 UTC, merged

2017-04-18 06:10 UTC, jaredleechn commented
0.8.0 will publish as soon as atool-build publish 0.9.4